# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cuis/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 680)
        MainWindow.setMinimumSize(QtCore.QSize(850, 680))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(9, 9, 830, 660))
        self.widget.setObjectName("widget")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(50, 80, 291, 121))
        self.label_5.setObjectName("label_5")
        self.pushButton_giris = QtWidgets.QPushButton(self.widget)
        self.pushButton_giris.setGeometry(QtCore.QRect(560, 360, 121, 81))
        self.pushButton_giris.setMinimumSize(QtCore.QSize(90, 60))
        self.pushButton_giris.setObjectName("pushButton_giris")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(9, 9, 410, 640))
        self.label.setStyleSheet("border-image:url(:/pic/login.jpeg);\n"
"\n"
"\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(410, 9, 410, 640))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton_cikis = QtWidgets.QPushButton(self.widget)
        self.pushButton_cikis.setGeometry(QtCore.QRect(750, 560, 61, 61))
        self.pushButton_cikis.setMaximumSize(QtCore.QSize(100, 80))
        self.pushButton_cikis.setText("")
        self.pushButton_cikis.setObjectName("pushButton_cikis")
        self.label.raise_()
        self.label_2.raise_()
        self.pushButton_giris.raise_()
        self.label_5.raise_()
        self.pushButton_cikis.raise_()
        self.lineEdit_kullanci_adi = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_kullanci_adi.setEnabled(True)
        self.lineEdit_kullanci_adi.setGeometry(QtCore.QRect(140, 9, 220, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_kullanci_adi.sizePolicy().hasHeightForWidth())
        self.lineEdit_kullanci_adi.setSizePolicy(sizePolicy)
        self.lineEdit_kullanci_adi.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_kullanci_adi.setObjectName("lineEdit_kullanci_adi")
        self.lineEdit_parola = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_parola.setGeometry(QtCore.QRect(140, 60, 220, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_parola.sizePolicy().hasHeightForWidth())
        self.lineEdit_parola.setSizePolicy(sizePolicy)
        self.lineEdit_parola.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_parola.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_parola.setObjectName("lineEdit_parola")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Yaşar Kütüphanesi"))
        self.pushButton_giris.setText(_translate("MainWindow", "Giriş"))
        self.lineEdit_kullanci_adi.setToolTip(_translate("MainWindow", "Kullanıcı Adını Girin"))
        self.lineEdit_parola.setToolTip(_translate("MainWindow", "Parolayı Girin"))
from bforms import media_rc
