# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cuis/user.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 680)
        MainWindow.setGeometry(240,20,1020,680)
        MainWindow.setMinimumSize(QtCore.QSize(900, 680))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 9, 1000, 680))
        self.label.setMinimumSize(QtCore.QSize(1000, 680))
        self.label.setStyleSheet("border-image: url(:/pic/colorful.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 20, 501, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(270, 560, 421, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridlayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridlayout.setContentsMargins(0, 0, 0, 0)
        self.gridlayout.setObjectName("gridlayout")
        self.pushButton_kaydet = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_kaydet.setMinimumSize(QtCore.QSize(90, 60))
        self.pushButton_kaydet.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_kaydet.setFont(font)
        self.pushButton_kaydet.setStyleSheet("QPushButton#pushButton_kaydet{\n"
"background-color: rgb(255, 181, 61);\n"
"border-radius:10px;}\n"
"QPushButton#pushButton_kaydet:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0.880682, x2:0.955, y2:0.0284091, stop:0.5 rgba(212, 75, 45, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:10px;}\n"
"QPushButton#pushButton_kaydet:pressed{\n"
"background-color:qlineargradient(spread:repeat, x1:0, y1:1, x2:0, y2:0, stop:0.301136 rgba(135, 88, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"padding-left:5px;\n"
"padding-top:6px;\n"
"border-radius:10px;}\n"
"\n"
"")
        self.pushButton_kaydet.setObjectName("pushButton_kaydet")
        self.gridlayout.addWidget(self.pushButton_kaydet, 0, 0, 1, 1)
        self.pushButton_cikis = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_cikis.setMinimumSize(QtCore.QSize(90, 60))
        self.pushButton_cikis.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_cikis.setFont(font)
        self.pushButton_cikis.setStyleSheet("QPushButton#pushButton_cikis{\n"
"background-color: rgb(255, 181, 61);\n"
"border-radius:10px;}\n"
"QPushButton#pushButton_cikis:hover{\n"
"background-color:qlineargradient(spread:repeat, x1:0, y1:1, x2:0, y2:0, stop:0.301136 rgba(135, 88, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:10px;}\n"
"QPushButton#pushButton_cikis:pressed{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0.880682, x2:0.955, y2:0.0284091, stop:0.5 rgba(212, 75, 45, 255), stop:1 rgba(255, 255, 255, 255));\n"
"padding-left:5px;\n"
"padding-top:6px;\n"
"border-radius:10px;}\n"
"\n"
"")
        self.pushButton_cikis.setObjectName("pushButton_cikis")
        self.gridlayout.addWidget(self.pushButton_cikis, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(320, 100, 331, 431))
        self.groupBox.setStyleSheet("border-color: rgba(255,255,255,0);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_kullanici_adi = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_kullanici_adi.setGeometry(QtCore.QRect(10, 20, 300, 30))
        self.lineEdit_kullanici_adi.setMinimumSize(QtCore.QSize(300, 30))
        self.lineEdit_kullanici_adi.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_kullanici_adi.setFont(font)
        self.lineEdit_kullanici_adi.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_kullanici_adi.setObjectName("lineEdit_kullanici_adi")
        self.lineEdit_sifre = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_sifre.setGeometry(QtCore.QRect(10, 70, 300, 30))
        self.lineEdit_sifre.setMinimumSize(QtCore.QSize(300, 30))
        self.lineEdit_sifre.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_sifre.setFont(font)
        self.lineEdit_sifre.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.lineEdit_sifre.setObjectName("lineEdit_sifre")
        self.lineEdit_adi = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_adi.setGeometry(QtCore.QRect(10, 130, 300, 30))
        self.lineEdit_adi.setMinimumSize(QtCore.QSize(300, 30))
        self.lineEdit_adi.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_adi.setFont(font)
        self.lineEdit_adi.setText("")
        self.lineEdit_adi.setObjectName("lineEdit_adi")
        self.lineEdit_sehir = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_sehir.setGeometry(QtCore.QRect(10, 370, 300, 30))
        self.lineEdit_sehir.setMinimumSize(QtCore.QSize(300, 30))
        self.lineEdit_sehir.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_sehir.setFont(font)
        self.lineEdit_sehir.setObjectName("lineEdit_sehir")
        self.lineEdit_soyadi = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_soyadi.setGeometry(QtCore.QRect(10, 190, 300, 30))
        self.lineEdit_soyadi.setMinimumSize(QtCore.QSize(300, 30))
        self.lineEdit_soyadi.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_soyadi.setFont(font)
        self.lineEdit_soyadi.setObjectName("lineEdit_soyadi")
        self.lineEdit_mail = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_mail.setGeometry(QtCore.QRect(10, 310, 300, 30))
        self.lineEdit_mail.setMinimumSize(QtCore.QSize(300, 30))
        self.lineEdit_mail.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_mail.setFont(font)
        self.lineEdit_mail.setText("")
        self.lineEdit_mail.setObjectName("lineEdit_mail")
        self.lineEdit_tel = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_tel.setGeometry(QtCore.QRect(10, 250, 300, 30))
        self.lineEdit_tel.setMinimumSize(QtCore.QSize(300, 30))
        self.lineEdit_tel.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_tel.setFont(font)
        self.lineEdit_tel.setObjectName("lineEdit_tel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(12)
        font.setItalic(True)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "K U L L A N I C I   G İ R İ Ş İ"))
        self.pushButton_kaydet.setText(_translate("MainWindow", "Kaydet"))
        self.pushButton_cikis.setText(_translate("MainWindow", "Çıkış"))
        self.lineEdit_kullanici_adi.setPlaceholderText(_translate("MainWindow", "Kullanıcı Adı"))
        self.lineEdit_sifre.setPlaceholderText(_translate("MainWindow", "Şifre"))
        self.lineEdit_adi.setPlaceholderText(_translate("MainWindow", "Adı"))
        self.lineEdit_sehir.setPlaceholderText(_translate("MainWindow", "Şehir"))
        self.lineEdit_soyadi.setPlaceholderText(_translate("MainWindow", "Soyadı"))
        self.lineEdit_mail.setPlaceholderText(_translate("MainWindow", "Mail Adresi"))
        self.lineEdit_tel.setPlaceholderText(_translate("MainWindow", "Telefon"))
import media.media_rc
